const {
  AndroidConfig,
  withAndroidManifest,
  withAppDelegate,
  withGradleProperties,
  withInfoPlist,
  withProjectBuildGradle,
} = require('expo/config-plugins');

const GRADLE_START = '// @generated by withGoogleNavigation';
const GRADLE_END = '// @end generated by withGoogleNavigation';

function withAndroidKey(config, apiKey) {
  return withAndroidManifest(config, (mod) => {
    if (!apiKey) return mod;
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      application,
      'com.google.android.geo.API_KEY',
      apiKey,
    );
    return mod;
  });
}

function withNavigationGradle(config) {
  config = withGradleProperties(config, (mod) => {
    const properties = mod.modResults.filter((item) => item.key !== 'android.enableJetifier');
    properties.push({ type: 'property', key: 'android.enableJetifier', value: 'true' });
    mod.modResults = properties;
    return mod;
  });

  return withProjectBuildGradle(config, (mod) => {
    const block = `${GRADLE_START}
allprojects {
    configurations.configureEach {
        // Navigation SDK bundles Maps SDK. Exclude react-native-maps' duplicate artifact.
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                android.compileOptions.coreLibraryDesugaringEnabled = true
                project.dependencies.add('coreLibraryDesugaring', 'com.android.tools:desugar_jdk_libs_nio:2.0.4')
            }
        }
    }
}
${GRADLE_END}`;
    const pattern = new RegExp(`${GRADLE_START}[\\s\\S]*?${GRADLE_END}`, 'm');
    mod.modResults.contents = pattern.test(mod.modResults.contents)
      ? mod.modResults.contents.replace(pattern, block)
      : `${mod.modResults.contents.trimEnd()}\n\n${block}\n`;
    return mod;
  });
}

function withIosNavigation(config, apiKey) {
  config = withInfoPlist(config, (mod) => {
    if (apiKey) mod.modResults.GMSApiKey = apiKey;
    return mod;
  });

  return withAppDelegate(config, (mod) => {
    if (!apiKey || mod.modResults.language !== 'swift') return mod;
    let contents = mod.modResults.contents;
    if (!contents.includes('import GoogleMaps')) {
      contents = contents.replace('import Expo', 'import Expo\nimport GoogleMaps');
    }
    const marker = '// Configure Google Navigation SDK';
    if (!contents.includes(marker)) {
      const anchor = 'return super.application(application, didFinishLaunchingWithOptions: launchOptions)';
      const setup = `${marker}\n    if let navigationKey = Bundle.main.object(forInfoDictionaryKey: "GMSApiKey") as? String, !navigationKey.isEmpty {\n      GMSServices.provideAPIKey(navigationKey)\n    }\n\n    `;
      if (!contents.includes(anchor)) {
        throw new Error('withGoogleNavigation could not find the Expo AppDelegate launch anchor.');
      }
      contents = contents.replace(anchor, `${setup}${anchor}`);
    }
    mod.modResults.contents = contents;
    return mod;
  });
}

module.exports = function withGoogleNavigation(config) {
  const androidApiKey = process.env.GOOGLE_NAVIGATION_ANDROID_API_KEY ?? '';
  const iosApiKey = process.env.GOOGLE_NAVIGATION_IOS_API_KEY ?? '';
  config = withAndroidKey(config, androidApiKey);
  config = withNavigationGradle(config);
  config = withIosNavigation(config, iosApiKey);
  return config;
};
