import type { DriverOffer, PastTrip, RiderRequest } from './rideModel';

// Frontend-only M2 fixtures standing in for matching results. Areas are 2-mile
// privacy areas (never addresses), matching how real profiles will appear.
export const driverOfferFixtures: DriverOffer[] = [
  {
    id: 'alex',
    driverName: 'Alex',
    startAreaLabel: 'Lake Grove area',
    campusLot: 'tabler',
    days: ['mon', 'wed', 'fri'],
    pickupTime: 7 * 60 + 55,
    arriveBy: 8 * 60 + 40,
    leaveAt: 17 * 60 + 15,
    seatsLeft: 2,
    vehicle: 'Gray Honda Civic',
    pickupSpot: 'Smith Haven Mall, Macy’s entrance',
    chatId: 'alex-chat',
  },
  {
    id: 'sarah',
    driverName: 'Sarah',
    startAreaLabel: 'Centereach area',
    campusLot: 'westSide',
    days: ['mon', 'tue', 'wed', 'thu'],
    pickupTime: 8 * 60 + 5,
    arriveBy: 8 * 60 + 50,
    leaveAt: 16 * 60 + 30,
    seatsLeft: 1,
    vehicle: 'White Toyota RAV4',
    pickupSpot: 'Centereach Park & Ride, Rte 25',
    chatId: 'sarah-chat',
  },
  {
    id: 'priya',
    driverName: 'Priya',
    startAreaLabel: 'Selden area',
    campusLot: 'roth',
    days: ['tue', 'thu'],
    pickupTime: 8 * 60 + 20,
    arriveBy: 9 * 60,
    leaveAt: 15 * 60,
    seatsLeft: 3,
    vehicle: 'Blue Subaru Outback',
    pickupSpot: 'Selden Stop & Shop, front lot',
  },
  {
    id: 'marcus',
    driverName: 'Marcus',
    startAreaLabel: 'Port Jefferson area',
    campusLot: 'lot40',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    pickupTime: 7 * 60 + 30,
    arriveBy: 8 * 60 + 15,
    leaveAt: 18 * 60,
    seatsLeft: 2,
    vehicle: 'Black Jeep Cherokee',
    pickupSpot: 'Port Jefferson LIRR station',
  },
  {
    id: 'jenna',
    driverName: 'Jenna',
    startAreaLabel: 'Smithtown area',
    campusLot: 'eastSide',
    days: ['mon', 'wed'],
    pickupTime: 9 * 60 + 10,
    arriveBy: 9 * 60 + 45,
    leaveAt: 14 * 60 + 30,
    seatsLeft: 1,
    vehicle: 'Red Mazda 3',
    pickupSpot: 'Smithtown LIRR station, south lot',
  },
  {
    id: 'dan',
    driverName: 'Dan',
    startAreaLabel: 'Hauppauge area',
    campusLot: 'tabler',
    days: ['fri'],
    pickupTime: 9 * 60 + 5,
    arriveBy: 9 * 60 + 50,
    leaveAt: 14 * 60 + 15,
    seatsLeft: 3,
    vehicle: 'Blue Honda CR-V',
    pickupSpot: 'Hauppauge Park & Ride, Exit 55',
  },
  {
    id: 'omar',
    driverName: 'Omar',
    startAreaLabel: 'Ronkonkoma area',
    campusLot: 'lot40',
    days: ['mon', 'wed', 'fri'],
    pickupTime: 8 * 60 + 15,
    arriveBy: 8 * 60 + 55,
    leaveAt: 17 * 60 + 45,
    seatsLeft: 3,
    vehicle: 'Silver Toyota Camry',
    pickupSpot: 'Ronkonkoma LIRR station, south lot',
  },
  {
    id: 'lena',
    driverName: 'Lena',
    startAreaLabel: 'Setauket area',
    campusLot: 'eastSide',
    days: ['tue', 'thu', 'fri'],
    pickupTime: 8 * 60 + 25,
    arriveBy: 8 * 60 + 45,
    leaveAt: 16 * 60,
    seatsLeft: 1,
    vehicle: 'Green Kia Soul',
    pickupSpot: 'Setauket Village Green, Main St',
  },
  {
    id: 'jordan',
    driverName: 'Jordan',
    startAreaLabel: 'Coram area',
    campusLot: 'westSide',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    pickupTime: 7 * 60 + 10,
    arriveBy: 7 * 60 + 50,
    leaveAt: 16 * 60 + 15,
    seatsLeft: 2,
    vehicle: 'Gray Ford Escape',
    pickupSpot: 'Coram Park & Ride, Rte 112',
  },
  {
    id: 'hannah',
    driverName: 'Hannah',
    startAreaLabel: 'Commack area',
    campusLot: 'roth',
    days: ['mon', 'wed'],
    pickupTime: 8 * 60 + 30,
    arriveBy: 9 * 60 + 20,
    // Morning only: she stays late for lab and doesn't offer a ride home.
    leaveAt: null,
    seatsLeft: 2,
    vehicle: 'White Hyundai Elantra',
    pickupSpot: 'Commack Target, front lot',
  },
];

export const riderRequestFixtures: RiderRequest[] = [
  {
    id: 'dev',
    riderName: 'Dev',
    startAreaLabel: 'Centereach area',
    campusLot: 'tabler',
    days: ['mon', 'wed'],
    arriveBy: 9 * 60,
    leaveAt: 17 * 60,
    addedMinutes: 6,
    pickupSpot: 'Centereach Library, Mark Tree Rd',
    note: 'I have a 9:30 lab on Mondays.',
  },
  {
    id: 'maya',
    riderName: 'Maya',
    startAreaLabel: 'Lake Ronkonkoma area',
    campusLot: 'westSide',
    days: ['tue', 'thu'],
    arriveBy: 9 * 60 + 15,
    leaveAt: 16 * 60,
    addedMinutes: 11,
    pickupSpot: 'Ronkonkoma LIRR station, north lot',
  },
  {
    id: 'chris',
    riderName: 'Chris',
    startAreaLabel: 'Stony Brook area',
    campusLot: 'roth',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    arriveBy: 9 * 60 + 15,
    leaveAt: 17 * 60 + 30,
    addedMinutes: 3,
    pickupSpot: 'Stony Brook LIRR station',
  },
  {
    id: 'sam',
    riderName: 'Sam',
    startAreaLabel: 'Mount Sinai area',
    campusLot: 'eastSide',
    days: ['tue'],
    arriveBy: 9 * 60 + 30,
    leaveAt: 15 * 60,
    addedMinutes: 8,
    pickupSpot: 'Mount Sinai Post Office, Rte 25A',
  },
  {
    id: 'nia',
    riderName: 'Nia',
    startAreaLabel: 'Holbrook area',
    campusLot: 'tabler',
    days: ['thu'],
    arriveBy: 9 * 60 + 30,
    leaveAt: 16 * 60 + 30,
    addedMinutes: 14,
    pickupSpot: 'Holbrook Country Club Plaza',
    note: 'Happy to chip in for gas.',
  },
];

// Demo history for the Past tab. Counted back from today so it always looks recent.
export const pastTripFixtures: PastTrip[] = [
  { id: 'past-1', daysAgo: 2, kind: 'ride', withName: 'Alex', campusLot: 'tabler', arrivedAt: 8 * 60 + 38, outcome: 'completed' },
  { id: 'past-6', daysAgo: 3, kind: 'drive', withName: 'Maya', campusLot: 'tabler', arrivedAt: 9 * 60 + 24, outcome: 'completed' },
  { id: 'past-2', daysAgo: 4, kind: 'ride', withName: 'Alex', campusLot: 'tabler', arrivedAt: 8 * 60 + 41, outcome: 'completed' },
  { id: 'past-3', daysAgo: 5, kind: 'ride', withName: 'Sarah', campusLot: 'westSide', arrivedAt: 8 * 60 + 50, outcome: 'skipped' },
  { id: 'past-4', daysAgo: 7, kind: 'ride', withName: 'Sarah', campusLot: 'westSide', arrivedAt: 8 * 60 + 47, outcome: 'completed' },
  { id: 'past-5', daysAgo: 9, kind: 'ride', withName: 'Jenna', campusLot: 'eastSide', arrivedAt: 9 * 60 + 45, outcome: 'cancelled' },
];
